// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/risingwavelabs/terraform-provider-risingwavecloud/internal/cloudsdk (interfaces: CloudClientInterface)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	uuid "github.com/google/uuid"
	cloudsdk "github.com/risingwavelabs/terraform-provider-risingwavecloud/internal/cloudsdk"
	apigen "github.com/risingwavelabs/terraform-provider-risingwavecloud/internal/cloudsdk/apigen/mgmt/v1"
	apigen0 "github.com/risingwavelabs/terraform-provider-risingwavecloud/internal/cloudsdk/apigen/mgmt/v2"
)

// MockCloudClientInterface is a mock of CloudClientInterface interface.
type MockCloudClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockCloudClientInterfaceMockRecorder
}

// MockCloudClientInterfaceMockRecorder is the mock recorder for MockCloudClientInterface.
type MockCloudClientInterfaceMockRecorder struct {
	mock *MockCloudClientInterface
}

// NewMockCloudClientInterface creates a new mock instance.
func NewMockCloudClientInterface(ctrl *gomock.Controller) *MockCloudClientInterface {
	mock := &MockCloudClientInterface{ctrl: ctrl}
	mock.recorder = &MockCloudClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloudClientInterface) EXPECT() *MockCloudClientInterfaceMockRecorder {
	return m.recorder
}

// AddAllowedIamRoleAwait mocks base method.
func (m *MockCloudClientInterface) AddAllowedIamRoleAwait(arg0 context.Context, arg1 uuid.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddAllowedIamRoleAwait", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddAllowedIamRoleAwait indicates an expected call of AddAllowedIamRoleAwait.
func (mr *MockCloudClientInterfaceMockRecorder) AddAllowedIamRoleAwait(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddAllowedIamRoleAwait", reflect.TypeOf((*MockCloudClientInterface)(nil).AddAllowedIamRoleAwait), arg0, arg1, arg2)
}

// CreateClusterAwait mocks base method.
func (m *MockCloudClientInterface) CreateClusterAwait(arg0 context.Context, arg1 string, arg2 apigen0.TenantRequestRequestBody) (*apigen0.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClusterAwait", arg0, arg1, arg2)
	ret0, _ := ret[0].(*apigen0.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClusterAwait indicates an expected call of CreateClusterAwait.
func (mr *MockCloudClientInterfaceMockRecorder) CreateClusterAwait(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClusterAwait", reflect.TypeOf((*MockCloudClientInterface)(nil).CreateClusterAwait), arg0, arg1, arg2)
}

// CreateClusterUser mocks base method.
func (m *MockCloudClientInterface) CreateClusterUser(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 string, arg4, arg5, arg6 bool) (*apigen0.DBUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClusterUser", arg0, arg1, arg2, arg3, arg4, arg5, arg6)
	ret0, _ := ret[0].(*apigen0.DBUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClusterUser indicates an expected call of CreateClusterUser.
func (mr *MockCloudClientInterfaceMockRecorder) CreateClusterUser(arg0, arg1, arg2, arg3, arg4, arg5, arg6 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClusterUser", reflect.TypeOf((*MockCloudClientInterface)(nil).CreateClusterUser), arg0, arg1, arg2, arg3, arg4, arg5, arg6)
}

// CreatePrivateLinkAwait mocks base method.
func (m *MockCloudClientInterface) CreatePrivateLinkAwait(arg0 context.Context, arg1 uuid.UUID, arg2 apigen0.PostPrivateLinkRequestBody) (*cloudsdk.PrivateLinkInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivateLinkAwait", arg0, arg1, arg2)
	ret0, _ := ret[0].(*cloudsdk.PrivateLinkInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePrivateLinkAwait indicates an expected call of CreatePrivateLinkAwait.
func (mr *MockCloudClientInterfaceMockRecorder) CreatePrivateLinkAwait(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivateLinkAwait", reflect.TypeOf((*MockCloudClientInterface)(nil).CreatePrivateLinkAwait), arg0, arg1, arg2)
}

// CreateResourceGroupAwait mocks base method.
func (m *MockCloudClientInterface) CreateResourceGroupAwait(arg0 context.Context, arg1 uuid.UUID, arg2 apigen0.CreateResourceGroupsRequestBody) (*apigen0.ResourceGroupDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateResourceGroupAwait", arg0, arg1, arg2)
	ret0, _ := ret[0].(*apigen0.ResourceGroupDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateResourceGroupAwait indicates an expected call of CreateResourceGroupAwait.
func (mr *MockCloudClientInterfaceMockRecorder) CreateResourceGroupAwait(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateResourceGroupAwait", reflect.TypeOf((*MockCloudClientInterface)(nil).CreateResourceGroupAwait), arg0, arg1, arg2)
}

// DeleteClusterByNsIDAwait mocks base method.
func (m *MockCloudClientInterface) DeleteClusterByNsIDAwait(arg0 context.Context, arg1 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClusterByNsIDAwait", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClusterByNsIDAwait indicates an expected call of DeleteClusterByNsIDAwait.
func (mr *MockCloudClientInterfaceMockRecorder) DeleteClusterByNsIDAwait(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClusterByNsIDAwait", reflect.TypeOf((*MockCloudClientInterface)(nil).DeleteClusterByNsIDAwait), arg0, arg1)
}

// DeleteClusterUser mocks base method.
func (m *MockCloudClientInterface) DeleteClusterUser(arg0 context.Context, arg1 uuid.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClusterUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClusterUser indicates an expected call of DeleteClusterUser.
func (mr *MockCloudClientInterfaceMockRecorder) DeleteClusterUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClusterUser", reflect.TypeOf((*MockCloudClientInterface)(nil).DeleteClusterUser), arg0, arg1, arg2)
}

// DeletePrivateLinkAwait mocks base method.
func (m *MockCloudClientInterface) DeletePrivateLinkAwait(arg0 context.Context, arg1, arg2 uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrivateLinkAwait", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePrivateLinkAwait indicates an expected call of DeletePrivateLinkAwait.
func (mr *MockCloudClientInterfaceMockRecorder) DeletePrivateLinkAwait(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrivateLinkAwait", reflect.TypeOf((*MockCloudClientInterface)(nil).DeletePrivateLinkAwait), arg0, arg1, arg2)
}

// DeleteResourceGroupAwait mocks base method.
func (m *MockCloudClientInterface) DeleteResourceGroupAwait(arg0 context.Context, arg1 uuid.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteResourceGroupAwait", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteResourceGroupAwait indicates an expected call of DeleteResourceGroupAwait.
func (mr *MockCloudClientInterfaceMockRecorder) DeleteResourceGroupAwait(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteResourceGroupAwait", reflect.TypeOf((*MockCloudClientInterface)(nil).DeleteResourceGroupAwait), arg0, arg1, arg2)
}

// GetAllowedIamRoles mocks base method.
func (m *MockCloudClientInterface) GetAllowedIamRoles(arg0 context.Context, arg1 uuid.UUID) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedIamRoles", arg0, arg1)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllowedIamRoles indicates an expected call of GetAllowedIamRoles.
func (mr *MockCloudClientInterfaceMockRecorder) GetAllowedIamRoles(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedIamRoles", reflect.TypeOf((*MockCloudClientInterface)(nil).GetAllowedIamRoles), arg0, arg1)
}

// GetAvailableComponentTypes mocks base method.
func (m *MockCloudClientInterface) GetAvailableComponentTypes(arg0 context.Context, arg1 string, arg2 apigen.TierId, arg3 string) ([]apigen.AvailableComponentType, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAvailableComponentTypes", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]apigen.AvailableComponentType)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAvailableComponentTypes indicates an expected call of GetAvailableComponentTypes.
func (mr *MockCloudClientInterfaceMockRecorder) GetAvailableComponentTypes(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAvailableComponentTypes", reflect.TypeOf((*MockCloudClientInterface)(nil).GetAvailableComponentTypes), arg0, arg1, arg2, arg3)
}

// GetBYOCCluster mocks base method.
func (m *MockCloudClientInterface) GetBYOCCluster(arg0 context.Context, arg1, arg2 string) (*apigen0.ManagedCluster, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBYOCCluster", arg0, arg1, arg2)
	ret0, _ := ret[0].(*apigen0.ManagedCluster)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBYOCCluster indicates an expected call of GetBYOCCluster.
func (mr *MockCloudClientInterfaceMockRecorder) GetBYOCCluster(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBYOCCluster", reflect.TypeOf((*MockCloudClientInterface)(nil).GetBYOCCluster), arg0, arg1, arg2)
}

// GetClusterByNsID mocks base method.
func (m *MockCloudClientInterface) GetClusterByNsID(arg0 context.Context, arg1 uuid.UUID) (*apigen0.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterByNsID", arg0, arg1)
	ret0, _ := ret[0].(*apigen0.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterByNsID indicates an expected call of GetClusterByNsID.
func (mr *MockCloudClientInterfaceMockRecorder) GetClusterByNsID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterByNsID", reflect.TypeOf((*MockCloudClientInterface)(nil).GetClusterByNsID), arg0, arg1)
}

// GetClusterByRegionAndName mocks base method.
func (m *MockCloudClientInterface) GetClusterByRegionAndName(arg0 context.Context, arg1, arg2 string) (*apigen0.Tenant, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterByRegionAndName", arg0, arg1, arg2)
	ret0, _ := ret[0].(*apigen0.Tenant)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterByRegionAndName indicates an expected call of GetClusterByRegionAndName.
func (mr *MockCloudClientInterfaceMockRecorder) GetClusterByRegionAndName(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterByRegionAndName", reflect.TypeOf((*MockCloudClientInterface)(nil).GetClusterByRegionAndName), arg0, arg1, arg2)
}

// GetClusterUser mocks base method.
func (m *MockCloudClientInterface) GetClusterUser(arg0 context.Context, arg1 uuid.UUID, arg2 string) (*apigen0.DBUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClusterUser", arg0, arg1, arg2)
	ret0, _ := ret[0].(*apigen0.DBUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClusterUser indicates an expected call of GetClusterUser.
func (mr *MockCloudClientInterfaceMockRecorder) GetClusterUser(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClusterUser", reflect.TypeOf((*MockCloudClientInterface)(nil).GetClusterUser), arg0, arg1, arg2)
}

// GetPrivateLink mocks base method.
func (m *MockCloudClientInterface) GetPrivateLink(arg0 context.Context, arg1 uuid.UUID) (*cloudsdk.PrivateLinkInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateLink", arg0, arg1)
	ret0, _ := ret[0].(*cloudsdk.PrivateLinkInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateLink indicates an expected call of GetPrivateLink.
func (mr *MockCloudClientInterfaceMockRecorder) GetPrivateLink(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateLink", reflect.TypeOf((*MockCloudClientInterface)(nil).GetPrivateLink), arg0, arg1)
}

// GetPrivateLinkByName mocks base method.
func (m *MockCloudClientInterface) GetPrivateLinkByName(arg0 context.Context, arg1 string) (*cloudsdk.PrivateLinkInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateLinkByName", arg0, arg1)
	ret0, _ := ret[0].(*cloudsdk.PrivateLinkInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateLinkByName indicates an expected call of GetPrivateLinkByName.
func (mr *MockCloudClientInterfaceMockRecorder) GetPrivateLinkByName(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateLinkByName", reflect.TypeOf((*MockCloudClientInterface)(nil).GetPrivateLinkByName), arg0, arg1)
}

// GetPrivateLinks mocks base method.
func (m *MockCloudClientInterface) GetPrivateLinks(arg0 context.Context) ([]cloudsdk.PrivateLinkInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateLinks", arg0)
	ret0, _ := ret[0].([]cloudsdk.PrivateLinkInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateLinks indicates an expected call of GetPrivateLinks.
func (mr *MockCloudClientInterfaceMockRecorder) GetPrivateLinks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateLinks", reflect.TypeOf((*MockCloudClientInterface)(nil).GetPrivateLinks), arg0)
}

// GetResourceGroup mocks base method.
func (m *MockCloudClientInterface) GetResourceGroup(arg0 context.Context, arg1 uuid.UUID, arg2 string) (*apigen0.ResourceGroupDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetResourceGroup", arg0, arg1, arg2)
	ret0, _ := ret[0].(*apigen0.ResourceGroupDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetResourceGroup indicates an expected call of GetResourceGroup.
func (mr *MockCloudClientInterfaceMockRecorder) GetResourceGroup(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetResourceGroup", reflect.TypeOf((*MockCloudClientInterface)(nil).GetResourceGroup), arg0, arg1, arg2)
}

// GetTiers mocks base method.
func (m *MockCloudClientInterface) GetTiers(arg0 context.Context, arg1 string) ([]apigen.Tier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTiers", arg0, arg1)
	ret0, _ := ret[0].([]apigen.Tier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTiers indicates an expected call of GetTiers.
func (mr *MockCloudClientInterfaceMockRecorder) GetTiers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTiers", reflect.TypeOf((*MockCloudClientInterface)(nil).GetTiers), arg0, arg1)
}

// Ping mocks base method.
func (m *MockCloudClientInterface) Ping(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockCloudClientInterfaceMockRecorder) Ping(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockCloudClientInterface)(nil).Ping), arg0)
}

// RemoveAllowedIamRoleAwait mocks base method.
func (m *MockCloudClientInterface) RemoveAllowedIamRoleAwait(arg0 context.Context, arg1 uuid.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveAllowedIamRoleAwait", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveAllowedIamRoleAwait indicates an expected call of RemoveAllowedIamRoleAwait.
func (mr *MockCloudClientInterfaceMockRecorder) RemoveAllowedIamRoleAwait(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveAllowedIamRoleAwait", reflect.TypeOf((*MockCloudClientInterface)(nil).RemoveAllowedIamRoleAwait), arg0, arg1, arg2)
}

// UpdateClusterImageByNsIDAwait mocks base method.
func (m *MockCloudClientInterface) UpdateClusterImageByNsIDAwait(arg0 context.Context, arg1 uuid.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClusterImageByNsIDAwait", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClusterImageByNsIDAwait indicates an expected call of UpdateClusterImageByNsIDAwait.
func (mr *MockCloudClientInterfaceMockRecorder) UpdateClusterImageByNsIDAwait(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClusterImageByNsIDAwait", reflect.TypeOf((*MockCloudClientInterface)(nil).UpdateClusterImageByNsIDAwait), arg0, arg1, arg2)
}

// UpdateClusterResourcesByNsIDAwait mocks base method.
func (m *MockCloudClientInterface) UpdateClusterResourcesByNsIDAwait(arg0 context.Context, arg1 uuid.UUID, arg2 apigen0.PostTenantResourcesRequestBody) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClusterResourcesByNsIDAwait", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClusterResourcesByNsIDAwait indicates an expected call of UpdateClusterResourcesByNsIDAwait.
func (mr *MockCloudClientInterfaceMockRecorder) UpdateClusterResourcesByNsIDAwait(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClusterResourcesByNsIDAwait", reflect.TypeOf((*MockCloudClientInterface)(nil).UpdateClusterResourcesByNsIDAwait), arg0, arg1, arg2)
}

// UpdateClusterUserPassword mocks base method.
func (m *MockCloudClientInterface) UpdateClusterUserPassword(arg0 context.Context, arg1 uuid.UUID, arg2, arg3 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClusterUserPassword", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClusterUserPassword indicates an expected call of UpdateClusterUserPassword.
func (mr *MockCloudClientInterfaceMockRecorder) UpdateClusterUserPassword(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClusterUserPassword", reflect.TypeOf((*MockCloudClientInterface)(nil).UpdateClusterUserPassword), arg0, arg1, arg2, arg3)
}

// UpdateResourceGroupAwait mocks base method.
func (m *MockCloudClientInterface) UpdateResourceGroupAwait(arg0 context.Context, arg1 uuid.UUID, arg2 string, arg3 apigen0.UpdateResourceGroupsRequestBody) (*apigen0.ResourceGroupDetails, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateResourceGroupAwait", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].(*apigen0.ResourceGroupDetails)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateResourceGroupAwait indicates an expected call of UpdateResourceGroupAwait.
func (mr *MockCloudClientInterfaceMockRecorder) UpdateResourceGroupAwait(arg0, arg1, arg2, arg3 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateResourceGroupAwait", reflect.TypeOf((*MockCloudClientInterface)(nil).UpdateResourceGroupAwait), arg0, arg1, arg2, arg3)
}

// UpdateRisingWaveConfigByNsIDAwait mocks base method.
func (m *MockCloudClientInterface) UpdateRisingWaveConfigByNsIDAwait(arg0 context.Context, arg1 uuid.UUID, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRisingWaveConfigByNsIDAwait", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRisingWaveConfigByNsIDAwait indicates an expected call of UpdateRisingWaveConfigByNsIDAwait.
func (mr *MockCloudClientInterfaceMockRecorder) UpdateRisingWaveConfigByNsIDAwait(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRisingWaveConfigByNsIDAwait", reflect.TypeOf((*MockCloudClientInterface)(nil).UpdateRisingWaveConfigByNsIDAwait), arg0, arg1, arg2)
}
