// Package apigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package apigen

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	ApiKeyAuthScopes = "ApiKeyAuth.Scopes"
	BearerAuthScopes = "BearerAuth.Scopes"
)

// Defines values for ClusterStatus.
const (
	ClusterStatusDeleted                 ClusterStatus = "Deleted"
	ClusterStatusFailed                  ClusterStatus = "Failed"
	ClusterStatusPendingResourceDeletion ClusterStatus = "PendingResourceDeletion"
	ClusterStatusProvisioned             ClusterStatus = "Provisioned"
	ClusterStatusReady                   ClusterStatus = "Ready"
	ClusterStatusTerminating             ClusterStatus = "Terminating"
	ClusterStatusUninitialized           ClusterStatus = "Uninitialized"
	ClusterStatusUpdating                ClusterStatus = "Updating"
)

// Defines values for MetaStoreType.
const (
	AwsRds      MetaStoreType = "aws_rds"
	AzrPostgres MetaStoreType = "azr_postgres"
	Etcd        MetaStoreType = "etcd"
	GcpCloudsql MetaStoreType = "gcp_cloudsql"
	Postgresql  MetaStoreType = "postgresql"
	SharingPg   MetaStoreType = "sharing_pg"
)

// Defines values for PrivateLinkConnectionState.
const (
	ACCEPTED          PrivateLinkConnectionState = "ACCEPTED"
	CLOSED            PrivateLinkConnectionState = "CLOSED"
	PENDING           PrivateLinkConnectionState = "PENDING"
	REJECTED          PrivateLinkConnectionState = "REJECTED"
	STATUSUNSPECIFIED PrivateLinkConnectionState = "STATUS_UNSPECIFIED"
)

// Defines values for PrivateLinkStatus.
const (
	CREATED  PrivateLinkStatus = "CREATED"
	CREATING PrivateLinkStatus = "CREATING"
	DELETING PrivateLinkStatus = "DELETING"
	ERROR    PrivateLinkStatus = "ERROR"
	UNKNOWN  PrivateLinkStatus = "UNKNOWN"
)

// Defines values for TenantHealthStatus.
const (
	Healthy   TenantHealthStatus = "Healthy"
	Unhealthy TenantHealthStatus = "Unhealthy"
	Unknown   TenantHealthStatus = "Unknown"
)

// Defines values for TenantStatus.
const (
	TenantStatusConfigUpdating         TenantStatus = "ConfigUpdating"
	TenantStatusCreating               TenantStatus = "Creating"
	TenantStatusDeleting               TenantStatus = "Deleting"
	TenantStatusExpired                TenantStatus = "Expired"
	TenantStatusExtensionDisabling     TenantStatus = "ExtensionDisabling"
	TenantStatusExtensionEnabling      TenantStatus = "ExtensionEnabling"
	TenantStatusExtensionUpdating      TenantStatus = "ExtensionUpdating"
	TenantStatusFailed                 TenantStatus = "Failed"
	TenantStatusMetaMigrating          TenantStatus = "MetaMigrating"
	TenantStatusQuiesced               TenantStatus = "Quiesced"
	TenantStatusResourceGroupsUpdating TenantStatus = "ResourceGroupsUpdating"
	TenantStatusRestoring              TenantStatus = "Restoring"
	TenantStatusRunning                TenantStatus = "Running"
	TenantStatusSnapshotting           TenantStatus = "Snapshotting"
	TenantStatusStarting               TenantStatus = "Starting"
	TenantStatusStopped                TenantStatus = "Stopped"
	TenantStatusStopping               TenantStatus = "Stopping"
	TenantStatusUpdating               TenantStatus = "Updating"
	TenantStatusUpgrading              TenantStatus = "Upgrading"
)

// Defines values for TenantUsageType.
const (
	General  TenantUsageType = "general"
	Pipeline TenantUsageType = "pipeline"
)

// Defines values for TierId.
const (
	BYOC      TierId = "BYOC"
	BYOK      TierId = "BYOK"
	Benchmark TierId = "Benchmark"
	Invited   TierId = "Invited"
	Standard  TierId = "Standard"
	Test      TierId = "Test"
)

// Defines values for QueryErrLogParamsTarget.
const (
	Message QueryErrLogParamsTarget = "message"
	Name    QueryErrLogParamsTarget = "name"
	Sink    QueryErrLogParamsTarget = "sink"
	Source  QueryErrLogParamsTarget = "source"
	Table   QueryErrLogParamsTarget = "table"
	Target  QueryErrLogParamsTarget = "target"
)

// Defines values for QueryErrLogParamsDirection.
const (
	Backward QueryErrLogParamsDirection = "backward"
	Forward  QueryErrLogParamsDirection = "forward"
)

// AvailableComponentType defines model for AvailableComponentType.
type AvailableComponentType struct {
	Cpu     string `json:"cpu"`
	Id      string `json:"id"`
	Maximum int    `json:"maximum"`
	Memory  string `json:"memory"`
}

// AvailableMetaStore defines model for AvailableMetaStore.
type AvailableMetaStore struct {
	AwsRds      *AvailableMetaStoreAwsRds      `json:"aws_rds,omitempty"`
	AzrPostgres *AvailableMetaStoreAzrPostgres `json:"azr_postgres,omitempty"`
	Etcd        *AvailableMetaStoreEtcd        `json:"etcd,omitempty"`
	GcpCloudsql *AvailableMetaStoreGcpCloudSql `json:"gcp_cloudsql,omitempty"`
	Postgresql  *AvailableMetaStorePostgreSql  `json:"postgresql,omitempty"`
	SharingPg   *AvailableMetaStoreSharingPg   `json:"sharing_pg,omitempty"`
}

// AvailableMetaStoreAwsRds defines model for AvailableMetaStoreAwsRds.
type AvailableMetaStoreAwsRds struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// AvailableMetaStoreAzrPostgres defines model for AvailableMetaStoreAzrPostgres.
type AvailableMetaStoreAzrPostgres struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// AvailableMetaStoreEtcd defines model for AvailableMetaStoreEtcd.
type AvailableMetaStoreEtcd struct {
	MaximumSizeGiB int                      `json:"maximumSizeGiB"`
	Nodes          []AvailableComponentType `json:"nodes"`
}

// AvailableMetaStoreGcpCloudSql defines model for AvailableMetaStoreGcpCloudSql.
type AvailableMetaStoreGcpCloudSql struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// AvailableMetaStorePostgreSql defines model for AvailableMetaStorePostgreSql.
type AvailableMetaStorePostgreSql struct {
	MaximumSizeGiB int                      `json:"maximumSizeGiB"`
	Nodes          []AvailableComponentType `json:"nodes"`
}

// AvailableMetaStoreSharingPg defines model for AvailableMetaStoreSharingPg.
type AvailableMetaStoreSharingPg struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// ClusterStatus defines model for ClusterStatus.
type ClusterStatus string

// ComponentResource defines model for ComponentResource.
type ComponentResource struct {
	ComponentTypeId string `json:"componentTypeId"`
	Cpu             string `json:"cpu"`
	Memory          string `json:"memory"`
	Replica         int    `json:"replica"`
}

// Endpoint defines model for Endpoint.
type Endpoint struct {
	Database                    string `json:"database"`
	Host                        string `json:"host"`
	Id                          int64  `json:"id"`
	InternalHost                string `json:"internalHost"`
	InternalPort                int    `json:"internalPort"`
	IsUserFacingEndpointPrivate *bool  `json:"isUserFacingEndpointPrivate,omitempty"`
	Options                     string `json:"options"`
	Port                        int    `json:"port"`
	TenantId                    int64  `json:"tenantId"`
}

// ErrLogQueryResult defines model for ErrLogQueryResult.
type ErrLogQueryResult struct {
	Status string     `json:"status"`
	Values [][]string `json:"values"`
}

// GetImageTagResponse defines model for GetImageTagResponse.
type GetImageTagResponse struct {
	ImageTag string `json:"imageTag"`
}

// ManagedCluster defines model for ManagedCluster.
type ManagedCluster struct {
	ClusterServiceAccount string             `json:"cluster_service_account"`
	Id                    uint64             `json:"id"`
	MasterUrl             string             `json:"master_url"`
	Name                  string             `json:"name"`
	Org                   openapi_types.UUID `json:"org"`
	ServingType           string             `json:"serving_type"`
	Settings              map[string]string  `json:"settings"`
	Status                ClusterStatus      `json:"status"`
	Token                 string             `json:"token"`
}

// MetaStoreAwsRds defines model for MetaStoreAwsRds.
type MetaStoreAwsRds struct {
	InstanceClass string `json:"instanceClass"`
	SizeGb        int    `json:"sizeGb"`
}

// MetaStoreAzrPostgres defines model for MetaStoreAzrPostgres.
type MetaStoreAzrPostgres struct {
	SizeGb int    `json:"sizeGb"`
	Sku    string `json:"sku"`
}

// MetaStoreEtcd defines model for MetaStoreEtcd.
type MetaStoreEtcd struct {
	Resource ComponentResource `json:"resource"`
	SizeGb   int               `json:"sizeGb"`
}

// MetaStoreGcpCloudSql defines model for MetaStoreGcpCloudSql.
type MetaStoreGcpCloudSql struct {
	SizeGb int    `json:"sizeGb"`
	Tier   string `json:"tier"`
}

// MetaStorePostgreSql defines model for MetaStorePostgreSql.
type MetaStorePostgreSql struct {
	Resource ComponentResource `json:"resource"`
	SizeGb   int               `json:"sizeGb"`
}

// MetaStoreSharingPg defines model for MetaStoreSharingPg.
type MetaStoreSharingPg struct {
	InstanceId string `json:"instanceId"`
}

// MetaStoreType defines model for MetaStoreType.
type MetaStoreType string

// PostPrivateLinkRequestBody defines model for PostPrivateLinkRequestBody.
type PostPrivateLinkRequestBody struct {
	ConnectionName string `json:"connectionName"`
	Target         string `json:"target"`
}

// PostPrivateLinkResponseBody defines model for PostPrivateLinkResponseBody.
type PostPrivateLinkResponseBody struct {
	ConnectionName string             `json:"connectionName"`
	Id             openapi_types.UUID `json:"id"`
}

// PrivateLink defines model for PrivateLink.
type PrivateLink struct {
	ConnectionName  string                     `json:"connectionName"`
	ConnectionState PrivateLinkConnectionState `json:"connectionState"`
	Endpoint        *string                    `json:"endpoint,omitempty"`
	Id              openapi_types.UUID         `json:"id"`
	Status          PrivateLinkStatus          `json:"status"`
	Target          *string                    `json:"target,omitempty"`
	TenantId        int64                      `json:"tenantId"`
}

// PrivateLinkConnectionState defines model for PrivateLink.ConnectionState.
type PrivateLinkConnectionState string

// PrivateLinkStatus defines model for PrivateLink.Status.
type PrivateLinkStatus string

// Tenant defines model for Tenant.
type Tenant struct {
	ClusterId            uint64             `json:"clusterId"`
	ClusterName          string             `json:"clusterName"`
	CreatedAt            time.Time          `json:"createdAt"`
	HealthStatus         TenantHealthStatus `json:"health_status"`
	Id                   uint64             `json:"id"`
	ImageTag             string             `json:"imageTag"`
	LatestImageTag       string             `json:"latestImageTag"`
	NsId                 openapi_types.UUID `json:"nsId"`
	OrgId                openapi_types.UUID `json:"orgId"`
	Region               string             `json:"region"`
	ResourceNamespace    string             `json:"resourceNamespace"`
	Resources            TenantResource     `json:"resources"`
	RwConfig             string             `json:"rw_config"`
	Status               TenantStatus       `json:"status"`
	TenantName           string             `json:"tenantName"`
	Tier                 TierId             `json:"tier"`
	UpcomingSnapshotTime *time.Time         `json:"upcomingSnapshotTime,omitempty"`
	UpdatedAt            time.Time          `json:"updatedAt"`
	UsageType            TenantUsageType    `json:"usageType"`
	UserId               uint64             `json:"userId"`
}

// TenantHealthStatus defines model for Tenant.HealthStatus.
type TenantHealthStatus string

// TenantStatus defines model for Tenant.Status.
type TenantStatus string

// TenantUsageType defines model for Tenant.UsageType.
type TenantUsageType string

// TenantResource defines model for TenantResource.
type TenantResource struct {
	Components     TenantResourceComponents   `json:"components"`
	ComputeCache   TenantResourceComputeCache `json:"computeCache"`
	MetaStore      *TenantResourceMetaStore   `json:"metaStore,omitempty"`
	ResourceGroups *TenantResourceGroupArray  `json:"resourceGroups,omitempty"`
}

// TenantResourceComponents defines model for TenantResourceComponents.
type TenantResourceComponents struct {
	Compactor  *ComponentResource `json:"compactor,omitempty"`
	Compute    *ComponentResource `json:"compute,omitempty"`
	Frontend   *ComponentResource `json:"frontend,omitempty"`
	Meta       *ComponentResource `json:"meta,omitempty"`
	Standalone *ComponentResource `json:"standalone,omitempty"`
}

// TenantResourceComputeCache defines model for TenantResourceComputeCache.
type TenantResourceComputeCache struct {
	SizeGb       int     `json:"sizeGb"`
	StorageClass *string `json:"storageClass,omitempty"`
}

// TenantResourceGroup defines model for TenantResourceGroup.
type TenantResourceGroup struct {
	ComputeCache TenantResourceComputeCache `json:"computeCache"`
	Name         string                     `json:"name"`
	Resource     ComponentResource          `json:"resource"`
}

// TenantResourceGroupArray defines model for TenantResourceGroupArray.
type TenantResourceGroupArray = []TenantResourceGroup

// TenantResourceMetaStore defines model for TenantResourceMetaStore.
type TenantResourceMetaStore struct {
	AwsRds      *MetaStoreAwsRds      `json:"aws_rds,omitempty"`
	AzrPostgres *MetaStoreAzrPostgres `json:"azr_postgres,omitempty"`
	Etcd        *MetaStoreEtcd        `json:"etcd,omitempty"`
	GcpCloudsql *MetaStoreGcpCloudSql `json:"gcp_cloudsql,omitempty"`
	Postgresql  *MetaStorePostgreSql  `json:"postgresql,omitempty"`
	Rwu         string                `json:"rwu"`
	SharingPg   *MetaStoreSharingPg   `json:"sharing_pg,omitempty"`
	Type        MetaStoreType         `json:"type"`
}

// Tier defines model for Tier.
type Tier struct {
	AvailableCompactorNodes            []AvailableComponentType `json:"availableCompactorNodes"`
	AvailableComputeNodes              []AvailableComponentType `json:"availableComputeNodes"`
	AvailableFrontendNodes             []AvailableComponentType `json:"availableFrontendNodes"`
	AvailableMetaNodes                 []AvailableComponentType `json:"availableMetaNodes"`
	AvailableMetaStore                 *AvailableMetaStore      `json:"availableMetaStore,omitempty"`
	AvailableStandaloneNodes           []AvailableComponentType `json:"availableStandaloneNodes"`
	Id                                 *TierId                  `json:"id,omitempty"`
	MaximumComputeNodeFileCacheSizeGiB int                      `json:"maximumComputeNodeFileCacheSizeGiB"`
	RetentionPeriod                    int                      `json:"retentionPeriod"`
	ValidityPeriod                     int                      `json:"validityPeriod"`
}

// TierArray defines model for TierArray.
type TierArray = []Tier

// TierId defines model for TierId.
type TierId string

// Tiers defines model for Tiers.
type Tiers struct {
	Tiers TierArray `json:"tiers"`
}

// BadRequestResponse defines model for BadRequestResponse.
type BadRequestResponse struct {
	Msg string `json:"msg"`
}

// DefaultResponse defines model for DefaultResponse.
type DefaultResponse struct {
	Msg string `json:"msg"`
}

// NotFoundResponse defines model for NotFoundResponse.
type NotFoundResponse struct {
	Msg string `json:"msg"`
}

// GetEndpointsParams defines parameters for GetEndpoints.
type GetEndpointsParams struct {
	TenantName *string `form:"tenantName,omitempty" json:"tenantName,omitempty"`
	TenantId   *uint64 `form:"tenantId,omitempty" json:"tenantId,omitempty"`
}

// QueryErrLogParams defines parameters for QueryErrLog.
type QueryErrLogParams struct {
	TenantId  uint64                      `form:"tenantId" json:"tenantId"`
	Target    QueryErrLogParamsTarget     `form:"target" json:"target"`
	TargetId  string                      `form:"targetId" json:"targetId"`
	Start     *time.Time                  `form:"start,omitempty" json:"start,omitempty"`
	End       *time.Time                  `form:"end,omitempty" json:"end,omitempty"`
	Direction *QueryErrLogParamsDirection `form:"direction,omitempty" json:"direction,omitempty"`
	Limit     *uint64                     `form:"limit,omitempty" json:"limit,omitempty"`
}

// QueryErrLogParamsTarget defines parameters for QueryErrLog.
type QueryErrLogParamsTarget string

// QueryErrLogParamsDirection defines parameters for QueryErrLog.
type QueryErrLogParamsDirection string

// GetTenantParams defines parameters for GetTenant.
type GetTenantParams struct {
	TenantId   *uint64 `form:"tenantId,omitempty" json:"tenantId,omitempty"`
	TenantName *string `form:"tenantName,omitempty" json:"tenantName,omitempty"`
}

// PutTenantTenantIdConfigRisingwaveTextBody defines parameters for PutTenantTenantIdConfigRisingwave.
type PutTenantTenantIdConfigRisingwaveTextBody = string

// PutTenantTenantIdConfigRisingwaveParams defines parameters for PutTenantTenantIdConfigRisingwave.
type PutTenantTenantIdConfigRisingwaveParams struct {
	Component *string `form:"component,omitempty" json:"component,omitempty"`
	NodeGroup *string `form:"nodeGroup,omitempty" json:"nodeGroup,omitempty"`
}

// PutTenantTenantIdConfigRisingwaveTextRequestBody defines body for PutTenantTenantIdConfigRisingwave for text/plain ContentType.
type PutTenantTenantIdConfigRisingwaveTextRequestBody = PutTenantTenantIdConfigRisingwaveTextBody

// PostTenantTenantIdPrivatelinksJSONRequestBody defines body for PostTenantTenantIdPrivatelinks for application/json ContentType.
type PostTenantTenantIdPrivatelinksJSONRequestBody = PostPrivateLinkRequestBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetByocClusterName request
	GetByocClusterName(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetEndpoints request
	GetEndpoints(ctx context.Context, params *GetEndpointsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// QueryErrLog request
	QueryErrLog(ctx context.Context, params *QueryErrLogParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetRootca request
	GetRootca(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTenant request
	GetTenant(ctx context.Context, params *GetTenantParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTenantTags request
	GetTenantTags(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutTenantTenantIdConfigRisingwaveWithBody request with any body
	PutTenantTenantIdConfigRisingwaveWithBody(ctx context.Context, tenantId uint64, params *PutTenantTenantIdConfigRisingwaveParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutTenantTenantIdConfigRisingwaveWithTextBody(ctx context.Context, tenantId uint64, params *PutTenantTenantIdConfigRisingwaveParams, body PutTenantTenantIdConfigRisingwaveTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteTenantTenantIdPrivatelinkPrivateLinkId request
	DeleteTenantTenantIdPrivatelinkPrivateLinkId(ctx context.Context, tenantId uint64, privateLinkId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTenantTenantIdPrivatelinkPrivateLinkId request
	GetTenantTenantIdPrivatelinkPrivateLinkId(ctx context.Context, tenantId uint64, privateLinkId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTenantTenantIdPrivatelinksWithBody request with any body
	PostTenantTenantIdPrivatelinksWithBody(ctx context.Context, tenantId uint64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostTenantTenantIdPrivatelinks(ctx context.Context, tenantId uint64, body PostTenantTenantIdPrivatelinksJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostTenantsTenantIdUnquiesce request
	PostTenantsTenantIdUnquiesce(ctx context.Context, tenantId uint64, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTiers request
	GetTiers(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetByocClusterName(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetByocClusterNameRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetEndpoints(ctx context.Context, params *GetEndpointsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetEndpointsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) QueryErrLog(ctx context.Context, params *QueryErrLogParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewQueryErrLogRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetRootca(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetRootcaRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTenant(ctx context.Context, params *GetTenantParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTenantRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTenantTags(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTenantTagsRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutTenantTenantIdConfigRisingwaveWithBody(ctx context.Context, tenantId uint64, params *PutTenantTenantIdConfigRisingwaveParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutTenantTenantIdConfigRisingwaveRequestWithBody(c.Server, tenantId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutTenantTenantIdConfigRisingwaveWithTextBody(ctx context.Context, tenantId uint64, params *PutTenantTenantIdConfigRisingwaveParams, body PutTenantTenantIdConfigRisingwaveTextRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutTenantTenantIdConfigRisingwaveRequestWithTextBody(c.Server, tenantId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteTenantTenantIdPrivatelinkPrivateLinkId(ctx context.Context, tenantId uint64, privateLinkId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteTenantTenantIdPrivatelinkPrivateLinkIdRequest(c.Server, tenantId, privateLinkId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTenantTenantIdPrivatelinkPrivateLinkId(ctx context.Context, tenantId uint64, privateLinkId openapi_types.UUID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTenantTenantIdPrivatelinkPrivateLinkIdRequest(c.Server, tenantId, privateLinkId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantTenantIdPrivatelinksWithBody(ctx context.Context, tenantId uint64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantTenantIdPrivatelinksRequestWithBody(c.Server, tenantId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantTenantIdPrivatelinks(ctx context.Context, tenantId uint64, body PostTenantTenantIdPrivatelinksJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantTenantIdPrivatelinksRequest(c.Server, tenantId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostTenantsTenantIdUnquiesce(ctx context.Context, tenantId uint64, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostTenantsTenantIdUnquiesceRequest(c.Server, tenantId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTiers(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTiersRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetByocClusterNameRequest generates requests for GetByocClusterName
func NewGetByocClusterNameRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "name", runtime.ParamLocationPath, name)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/byoc-cluster/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetEndpointsRequest generates requests for GetEndpoints
func NewGetEndpointsRequest(server string, params *GetEndpointsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/endpoints")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.TenantName != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tenantName", runtime.ParamLocationQuery, *params.TenantName); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.TenantId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tenantId", runtime.ParamLocationQuery, *params.TenantId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewQueryErrLogRequest generates requests for QueryErrLog
func NewQueryErrLogRequest(server string, params *QueryErrLogParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/log/queryError")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tenantId", runtime.ParamLocationQuery, params.TenantId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "target", runtime.ParamLocationQuery, params.Target); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "targetId", runtime.ParamLocationQuery, params.TargetId); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		if params.Start != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "start", runtime.ParamLocationQuery, *params.Start); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.End != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "end", runtime.ParamLocationQuery, *params.End); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Direction != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "direction", runtime.ParamLocationQuery, *params.Direction); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Limit != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "limit", runtime.ParamLocationQuery, *params.Limit); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetRootcaRequest generates requests for GetRootca
func NewGetRootcaRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/rootca")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTenantRequest generates requests for GetTenant
func NewGetTenantRequest(server string, params *GetTenantParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.TenantId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tenantId", runtime.ParamLocationQuery, *params.TenantId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.TenantName != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "tenantName", runtime.ParamLocationQuery, *params.TenantName); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTenantTagsRequest generates requests for GetTenantTags
func NewGetTenantTagsRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant/tags")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutTenantTenantIdConfigRisingwaveRequestWithTextBody calls the generic PutTenantTenantIdConfigRisingwave builder with text/plain body
func NewPutTenantTenantIdConfigRisingwaveRequestWithTextBody(server string, tenantId uint64, params *PutTenantTenantIdConfigRisingwaveParams, body PutTenantTenantIdConfigRisingwaveTextRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyReader = strings.NewReader(string(body))
	return NewPutTenantTenantIdConfigRisingwaveRequestWithBody(server, tenantId, params, "text/plain", bodyReader)
}

// NewPutTenantTenantIdConfigRisingwaveRequestWithBody generates requests for PutTenantTenantIdConfigRisingwave with any type of body
func NewPutTenantTenantIdConfigRisingwaveRequestWithBody(server string, tenantId uint64, params *PutTenantTenantIdConfigRisingwaveParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenantId", runtime.ParamLocationPath, tenantId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant/%s/config/risingwave", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Component != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "component", runtime.ParamLocationQuery, *params.Component); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.NodeGroup != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "nodeGroup", runtime.ParamLocationQuery, *params.NodeGroup); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteTenantTenantIdPrivatelinkPrivateLinkIdRequest generates requests for DeleteTenantTenantIdPrivatelinkPrivateLinkId
func NewDeleteTenantTenantIdPrivatelinkPrivateLinkIdRequest(server string, tenantId uint64, privateLinkId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenantId", runtime.ParamLocationPath, tenantId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "privateLinkId", runtime.ParamLocationPath, privateLinkId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant/%s/privatelink/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTenantTenantIdPrivatelinkPrivateLinkIdRequest generates requests for GetTenantTenantIdPrivatelinkPrivateLinkId
func NewGetTenantTenantIdPrivatelinkPrivateLinkIdRequest(server string, tenantId uint64, privateLinkId openapi_types.UUID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenantId", runtime.ParamLocationPath, tenantId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "privateLinkId", runtime.ParamLocationPath, privateLinkId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant/%s/privatelink/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostTenantTenantIdPrivatelinksRequest calls the generic PostTenantTenantIdPrivatelinks builder with application/json body
func NewPostTenantTenantIdPrivatelinksRequest(server string, tenantId uint64, body PostTenantTenantIdPrivatelinksJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostTenantTenantIdPrivatelinksRequestWithBody(server, tenantId, "application/json", bodyReader)
}

// NewPostTenantTenantIdPrivatelinksRequestWithBody generates requests for PostTenantTenantIdPrivatelinks with any type of body
func NewPostTenantTenantIdPrivatelinksRequestWithBody(server string, tenantId uint64, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenantId", runtime.ParamLocationPath, tenantId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenant/%s/privatelinks", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewPostTenantsTenantIdUnquiesceRequest generates requests for PostTenantsTenantIdUnquiesce
func NewPostTenantsTenantIdUnquiesceRequest(server string, tenantId uint64) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "tenantId", runtime.ParamLocationPath, tenantId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tenants/%s/unquiesce", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetTiersRequest generates requests for GetTiers
func NewGetTiersRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/tiers")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetByocClusterNameWithResponse request
	GetByocClusterNameWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*GetByocClusterNameResponse, error)

	// GetEndpointsWithResponse request
	GetEndpointsWithResponse(ctx context.Context, params *GetEndpointsParams, reqEditors ...RequestEditorFn) (*GetEndpointsResponse, error)

	// QueryErrLogWithResponse request
	QueryErrLogWithResponse(ctx context.Context, params *QueryErrLogParams, reqEditors ...RequestEditorFn) (*QueryErrLogResponse, error)

	// GetRootcaWithResponse request
	GetRootcaWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetRootcaResponse, error)

	// GetTenantWithResponse request
	GetTenantWithResponse(ctx context.Context, params *GetTenantParams, reqEditors ...RequestEditorFn) (*GetTenantResponse, error)

	// GetTenantTagsWithResponse request
	GetTenantTagsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetTenantTagsResponse, error)

	// PutTenantTenantIdConfigRisingwaveWithBodyWithResponse request with any body
	PutTenantTenantIdConfigRisingwaveWithBodyWithResponse(ctx context.Context, tenantId uint64, params *PutTenantTenantIdConfigRisingwaveParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutTenantTenantIdConfigRisingwaveResponse, error)

	PutTenantTenantIdConfigRisingwaveWithTextBodyWithResponse(ctx context.Context, tenantId uint64, params *PutTenantTenantIdConfigRisingwaveParams, body PutTenantTenantIdConfigRisingwaveTextRequestBody, reqEditors ...RequestEditorFn) (*PutTenantTenantIdConfigRisingwaveResponse, error)

	// DeleteTenantTenantIdPrivatelinkPrivateLinkIdWithResponse request
	DeleteTenantTenantIdPrivatelinkPrivateLinkIdWithResponse(ctx context.Context, tenantId uint64, privateLinkId openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteTenantTenantIdPrivatelinkPrivateLinkIdResponse, error)

	// GetTenantTenantIdPrivatelinkPrivateLinkIdWithResponse request
	GetTenantTenantIdPrivatelinkPrivateLinkIdWithResponse(ctx context.Context, tenantId uint64, privateLinkId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetTenantTenantIdPrivatelinkPrivateLinkIdResponse, error)

	// PostTenantTenantIdPrivatelinksWithBodyWithResponse request with any body
	PostTenantTenantIdPrivatelinksWithBodyWithResponse(ctx context.Context, tenantId uint64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantTenantIdPrivatelinksResponse, error)

	PostTenantTenantIdPrivatelinksWithResponse(ctx context.Context, tenantId uint64, body PostTenantTenantIdPrivatelinksJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantTenantIdPrivatelinksResponse, error)

	// PostTenantsTenantIdUnquiesceWithResponse request
	PostTenantsTenantIdUnquiesceWithResponse(ctx context.Context, tenantId uint64, reqEditors ...RequestEditorFn) (*PostTenantsTenantIdUnquiesceResponse, error)

	// GetTiersWithResponse request
	GetTiersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetTiersResponse, error)
}

type GetByocClusterNameResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ManagedCluster
	JSON404      *DefaultResponse
}

// Status returns HTTPResponse.Status
func (r GetByocClusterNameResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetByocClusterNameResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetEndpointsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Endpoint
	JSON404      *NotFoundResponse
}

// Status returns HTTPResponse.Status
func (r GetEndpointsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetEndpointsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type QueryErrLogResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ErrLogQueryResult
	JSON400      *BadRequestResponse
}

// Status returns HTTPResponse.Status
func (r QueryErrLogResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r QueryErrLogResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetRootcaResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r GetRootcaResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetRootcaResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTenantResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Tenant
	JSON404      *NotFoundResponse
}

// Status returns HTTPResponse.Status
func (r GetTenantResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTenantResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTenantTagsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetImageTagResponse
}

// Status returns HTTPResponse.Status
func (r GetTenantTagsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTenantTagsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutTenantTenantIdConfigRisingwaveResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *BadRequestResponse
	JSON404      *NotFoundResponse
	JSON409      *DefaultResponse
}

// Status returns HTTPResponse.Status
func (r PutTenantTenantIdConfigRisingwaveResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutTenantTenantIdConfigRisingwaveResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteTenantTenantIdPrivatelinkPrivateLinkIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *DefaultResponse
	JSON400      *BadRequestResponse
}

// Status returns HTTPResponse.Status
func (r DeleteTenantTenantIdPrivatelinkPrivateLinkIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteTenantTenantIdPrivatelinkPrivateLinkIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTenantTenantIdPrivatelinkPrivateLinkIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *PrivateLink
	JSON404      *NotFoundResponse
}

// Status returns HTTPResponse.Status
func (r GetTenantTenantIdPrivatelinkPrivateLinkIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTenantTenantIdPrivatelinkPrivateLinkIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTenantTenantIdPrivatelinksResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON202      *PostPrivateLinkResponseBody
	JSON400      *BadRequestResponse
}

// Status returns HTTPResponse.Status
func (r PostTenantTenantIdPrivatelinksResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTenantTenantIdPrivatelinksResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostTenantsTenantIdUnquiesceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostTenantsTenantIdUnquiesceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostTenantsTenantIdUnquiesceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTiersResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Tiers
}

// Status returns HTTPResponse.Status
func (r GetTiersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTiersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetByocClusterNameWithResponse request returning *GetByocClusterNameResponse
func (c *ClientWithResponses) GetByocClusterNameWithResponse(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*GetByocClusterNameResponse, error) {
	rsp, err := c.GetByocClusterName(ctx, name, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetByocClusterNameResponse(rsp)
}

// GetEndpointsWithResponse request returning *GetEndpointsResponse
func (c *ClientWithResponses) GetEndpointsWithResponse(ctx context.Context, params *GetEndpointsParams, reqEditors ...RequestEditorFn) (*GetEndpointsResponse, error) {
	rsp, err := c.GetEndpoints(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetEndpointsResponse(rsp)
}

// QueryErrLogWithResponse request returning *QueryErrLogResponse
func (c *ClientWithResponses) QueryErrLogWithResponse(ctx context.Context, params *QueryErrLogParams, reqEditors ...RequestEditorFn) (*QueryErrLogResponse, error) {
	rsp, err := c.QueryErrLog(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseQueryErrLogResponse(rsp)
}

// GetRootcaWithResponse request returning *GetRootcaResponse
func (c *ClientWithResponses) GetRootcaWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetRootcaResponse, error) {
	rsp, err := c.GetRootca(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetRootcaResponse(rsp)
}

// GetTenantWithResponse request returning *GetTenantResponse
func (c *ClientWithResponses) GetTenantWithResponse(ctx context.Context, params *GetTenantParams, reqEditors ...RequestEditorFn) (*GetTenantResponse, error) {
	rsp, err := c.GetTenant(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTenantResponse(rsp)
}

// GetTenantTagsWithResponse request returning *GetTenantTagsResponse
func (c *ClientWithResponses) GetTenantTagsWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetTenantTagsResponse, error) {
	rsp, err := c.GetTenantTags(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTenantTagsResponse(rsp)
}

// PutTenantTenantIdConfigRisingwaveWithBodyWithResponse request with arbitrary body returning *PutTenantTenantIdConfigRisingwaveResponse
func (c *ClientWithResponses) PutTenantTenantIdConfigRisingwaveWithBodyWithResponse(ctx context.Context, tenantId uint64, params *PutTenantTenantIdConfigRisingwaveParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutTenantTenantIdConfigRisingwaveResponse, error) {
	rsp, err := c.PutTenantTenantIdConfigRisingwaveWithBody(ctx, tenantId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutTenantTenantIdConfigRisingwaveResponse(rsp)
}

func (c *ClientWithResponses) PutTenantTenantIdConfigRisingwaveWithTextBodyWithResponse(ctx context.Context, tenantId uint64, params *PutTenantTenantIdConfigRisingwaveParams, body PutTenantTenantIdConfigRisingwaveTextRequestBody, reqEditors ...RequestEditorFn) (*PutTenantTenantIdConfigRisingwaveResponse, error) {
	rsp, err := c.PutTenantTenantIdConfigRisingwaveWithTextBody(ctx, tenantId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutTenantTenantIdConfigRisingwaveResponse(rsp)
}

// DeleteTenantTenantIdPrivatelinkPrivateLinkIdWithResponse request returning *DeleteTenantTenantIdPrivatelinkPrivateLinkIdResponse
func (c *ClientWithResponses) DeleteTenantTenantIdPrivatelinkPrivateLinkIdWithResponse(ctx context.Context, tenantId uint64, privateLinkId openapi_types.UUID, reqEditors ...RequestEditorFn) (*DeleteTenantTenantIdPrivatelinkPrivateLinkIdResponse, error) {
	rsp, err := c.DeleteTenantTenantIdPrivatelinkPrivateLinkId(ctx, tenantId, privateLinkId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteTenantTenantIdPrivatelinkPrivateLinkIdResponse(rsp)
}

// GetTenantTenantIdPrivatelinkPrivateLinkIdWithResponse request returning *GetTenantTenantIdPrivatelinkPrivateLinkIdResponse
func (c *ClientWithResponses) GetTenantTenantIdPrivatelinkPrivateLinkIdWithResponse(ctx context.Context, tenantId uint64, privateLinkId openapi_types.UUID, reqEditors ...RequestEditorFn) (*GetTenantTenantIdPrivatelinkPrivateLinkIdResponse, error) {
	rsp, err := c.GetTenantTenantIdPrivatelinkPrivateLinkId(ctx, tenantId, privateLinkId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTenantTenantIdPrivatelinkPrivateLinkIdResponse(rsp)
}

// PostTenantTenantIdPrivatelinksWithBodyWithResponse request with arbitrary body returning *PostTenantTenantIdPrivatelinksResponse
func (c *ClientWithResponses) PostTenantTenantIdPrivatelinksWithBodyWithResponse(ctx context.Context, tenantId uint64, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostTenantTenantIdPrivatelinksResponse, error) {
	rsp, err := c.PostTenantTenantIdPrivatelinksWithBody(ctx, tenantId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantTenantIdPrivatelinksResponse(rsp)
}

func (c *ClientWithResponses) PostTenantTenantIdPrivatelinksWithResponse(ctx context.Context, tenantId uint64, body PostTenantTenantIdPrivatelinksJSONRequestBody, reqEditors ...RequestEditorFn) (*PostTenantTenantIdPrivatelinksResponse, error) {
	rsp, err := c.PostTenantTenantIdPrivatelinks(ctx, tenantId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantTenantIdPrivatelinksResponse(rsp)
}

// PostTenantsTenantIdUnquiesceWithResponse request returning *PostTenantsTenantIdUnquiesceResponse
func (c *ClientWithResponses) PostTenantsTenantIdUnquiesceWithResponse(ctx context.Context, tenantId uint64, reqEditors ...RequestEditorFn) (*PostTenantsTenantIdUnquiesceResponse, error) {
	rsp, err := c.PostTenantsTenantIdUnquiesce(ctx, tenantId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostTenantsTenantIdUnquiesceResponse(rsp)
}

// GetTiersWithResponse request returning *GetTiersResponse
func (c *ClientWithResponses) GetTiersWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetTiersResponse, error) {
	rsp, err := c.GetTiers(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTiersResponse(rsp)
}

// ParseGetByocClusterNameResponse parses an HTTP response from a GetByocClusterNameWithResponse call
func ParseGetByocClusterNameResponse(rsp *http.Response) (*GetByocClusterNameResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetByocClusterNameResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ManagedCluster
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest DefaultResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetEndpointsResponse parses an HTTP response from a GetEndpointsWithResponse call
func ParseGetEndpointsResponse(rsp *http.Response) (*GetEndpointsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetEndpointsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Endpoint
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseQueryErrLogResponse parses an HTTP response from a QueryErrLogWithResponse call
func ParseQueryErrLogResponse(rsp *http.Response) (*QueryErrLogResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &QueryErrLogResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ErrLogQueryResult
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetRootcaResponse parses an HTTP response from a GetRootcaWithResponse call
func ParseGetRootcaResponse(rsp *http.Response) (*GetRootcaResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetRootcaResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetTenantResponse parses an HTTP response from a GetTenantWithResponse call
func ParseGetTenantResponse(rsp *http.Response) (*GetTenantResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTenantResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Tenant
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetTenantTagsResponse parses an HTTP response from a GetTenantTagsWithResponse call
func ParseGetTenantTagsResponse(rsp *http.Response) (*GetTenantTagsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTenantTagsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetImageTagResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePutTenantTenantIdConfigRisingwaveResponse parses an HTTP response from a PutTenantTenantIdConfigRisingwaveWithResponse call
func ParsePutTenantTenantIdConfigRisingwaveResponse(rsp *http.Response) (*PutTenantTenantIdConfigRisingwaveResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutTenantTenantIdConfigRisingwaveResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest DefaultResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseDeleteTenantTenantIdPrivatelinkPrivateLinkIdResponse parses an HTTP response from a DeleteTenantTenantIdPrivatelinkPrivateLinkIdWithResponse call
func ParseDeleteTenantTenantIdPrivatelinkPrivateLinkIdResponse(rsp *http.Response) (*DeleteTenantTenantIdPrivatelinkPrivateLinkIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteTenantTenantIdPrivatelinkPrivateLinkIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest DefaultResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParseGetTenantTenantIdPrivatelinkPrivateLinkIdResponse parses an HTTP response from a GetTenantTenantIdPrivatelinkPrivateLinkIdWithResponse call
func ParseGetTenantTenantIdPrivatelinkPrivateLinkIdResponse(rsp *http.Response) (*GetTenantTenantIdPrivatelinkPrivateLinkIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTenantTenantIdPrivatelinkPrivateLinkIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PrivateLink
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest NotFoundResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParsePostTenantTenantIdPrivatelinksResponse parses an HTTP response from a PostTenantTenantIdPrivatelinksWithResponse call
func ParsePostTenantTenantIdPrivatelinksResponse(rsp *http.Response) (*PostTenantTenantIdPrivatelinksResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTenantTenantIdPrivatelinksResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest PostPrivateLinkResponseBody
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest BadRequestResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}

// ParsePostTenantsTenantIdUnquiesceResponse parses an HTTP response from a PostTenantsTenantIdUnquiesceWithResponse call
func ParsePostTenantsTenantIdUnquiesceResponse(rsp *http.Response) (*PostTenantsTenantIdUnquiesceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostTenantsTenantIdUnquiesceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetTiersResponse parses an HTTP response from a GetTiersWithResponse call
func ParseGetTiersResponse(rsp *http.Response) (*GetTiersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTiersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Tiers
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
